title:            Scribble
description:      My Blog
url:              brennan.codes # Site url.
signoff:          Patrick # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
# facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:patrick@brennan.codes
    external:     true
  - name:         GitHub
    url:          http://github.com/ulbanata
    external:     true
  - name:         StormChaser
    url:          http://stormchaser.herokuapp.com
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
exclude: [vendor]
